// Generated by CoffeeScript 1.6.1
(function() {
  var Cloverscratcher, root;

  if (typeof $ !== "undefined" && $ !== null) {
    $(document).ready(function() {
      var cloverscratcher, scratch;
      cloverscratcher = new Cloverscratcher;
      cloverscratcher.start();
      scratch = function(leaf) {
        return $(this).addClass('scratched');
      };
      return $('div.cloverleaf p').click(scratch);
    });
  }

  Cloverscratcher = (function() {

    function Cloverscratcher() {
      var font_case, i, _i;
      this.symbols = [];
      font_case = ['h', 's', 'y', 'h'];
      for (i = _i = 0; _i <= 3; i = ++_i) {
        this.symbols[i] = font_case[Math.floor(Math.random() * 4)];
      }
    }

    Cloverscratcher.prototype.start = function() {
      var i, _i, _results;
      _results = [];
      for (i = _i = 0; _i <= 3; i = ++_i) {
        _results.push($('div.cloverleaf#leaf-' + i + ' p').html(this.symbols[i]));
      }
      return _results;
    };

    return Cloverscratcher;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Cloverscratcher = Cloverscratcher;

}).call(this);
