// Generated by CoffeeScript 1.6.1
(function() {
  var Cloverscratcher, root,
    _this = this;

  if (typeof $ !== "undefined" && $ !== null) {
    $(document).ready(function() {
      var cloverscratcher;
      cloverscratcher = new Cloverscratcher;
      cloverscratcher.start();
      cloverscratcher.hedgehog.on('mouseenter', cloverscratcher.toggleInfo);
      cloverscratcher.hedgehog.on('mouseleave', cloverscratcher.toggleInfo);
      cloverscratcher.ticket.on('mouseenter', '.cloverleaf p', cloverscratcher.toggleInfo);
      cloverscratcher.ticket.on('mouseleave', '.cloverleaf p', cloverscratcher.toggleInfo);
      return cloverscratcher.ticket.on('click', '.cloverleaf p', cloverscratcher.scratch);
    });
  }

  Cloverscratcher = (function() {

    function Cloverscratcher() {
      var _this = this;
      this.toggleInfo = function() {
        return Cloverscratcher.prototype.toggleInfo.apply(_this, arguments);
      };
      this.ticket = $('div#ticket');
      this.hedgehog = $('div#hedgehog');
      this.symbols = ['h', 'h', 'h', 'h'];
    }

    Cloverscratcher.prototype.toggleInfo = function() {
      this.ticket.find('div.cloverleaf p').toggleClass('info');
      this.hedgehog.toggleClass('info');
      return this.hedgehog.find('em').fadeToggle();
    };

    Cloverscratcher.prototype.start = function() {
      var i, _i, _results;
      $('#calendar').hide();
      _results = [];
      for (i = _i = 0; _i <= 3; i = ++_i) {
        _results.push($('div.cloverleaf#leaf-' + i + ' p').append(this.symbols[i]));
      }
      return _results;
    };

    Cloverscratcher.prototype.scratch = function() {
      $(this).addClass('scratched').removeClass('covered');
      $('.cloverleaf p.scratched span').fadeOut(2000);
      if ($('div.cloverleaf p.covered').length === 0) {
        return Cloverscratcher.prototype.finish();
      }
    };

    Cloverscratcher.prototype.finish = function() {
      var delay, display_cal, hide_game, write_note;
      hide_game = function() {
        return $('#ticket').fadeOut(display_cal);
      };
      display_cal = function() {
        $('#calendar').fadeIn(3000, write_note);
        return $('body').addClass('discovered');
      };
      write_note = function() {
        $('#note').html("Mariage de<br/> Nelly & Pierre");
        new window.TypingText(document.getElementById('note'));
        return window.TypingText.runAll();
      };
      delay = function(time, fn, args) {
        return setTimeout(fn, time, args);
      };
      return delay(2500, hide_game);
    };

    return Cloverscratcher;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Cloverscratcher = Cloverscratcher;

}).call(this);
